{"name": "Получение заказов неавторизованным пользователем", "status": "passed", "description": "Тест проверяет, что неавторизованный пользователь не может получить список заказов и получает ошибку", "steps": [{"name": "Получить все заказы конкретного пользователя", "status": "passed", "parameters": [{"name": "headers", "value": "None"}], "start": 1718404950938, "stop": 1718404951644}], "start": 1718404950938, "stop": 1718404951646, "uuid": "d3a4dd68-3647-40cf-b40a-e48ba2576bc0", "historyId": "c53dd8e79ba985211f67319f8d7b949c", "testCaseId": "c53dd8e79ba985211f67319f8d7b949c", "fullName": "tests.test_receive_user_orders.TestReceiveUserOrders#test_unauthorized_user_cannot_get_orders", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_receive_user_orders"}, {"name": "subSuite", "value": "TestReceiveUserOrders"}, {"name": "host", "value": "DESKTOP-212965U"}, {"name": "thread", "value": "15752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_receive_user_orders"}]}