{"name": "Проверка успешной авторизации существующим пользователем", "status": "passed", "description": "Тест проверяет, что можно авторизоваться уже существующим пользователем", "start": 1718404956279, "stop": 1718404957150, "uuid": "55c91c6a-0021-4450-93e8-e7d00117a29b", "historyId": "1433faec85c7c370884c3c67e482fcbb", "testCaseId": "1433faec85c7c370884c3c67e482fcbb", "fullName": "tests.test_user_login.TestUserLogin#test_user_can_login_with_existing_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-212965U"}, {"name": "thread", "value": "15752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}